# Generated by Django 3.1.12 on 2024-11-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
