# Generated by Django 3.1.12 on 2025-04-23 08:50

from django.db import migrations, models
import djongo.models.fields
import ocr.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=36)),
                ('class_name', models.CharField(max_length=50)),
                ('academic_performance', models.CharField(max_length=50)),
                ('conduct', models.CharField(max_length=50)),
                ('subjects', djongo.models.fields.ArrayField(model_container=ocr.models.Subject)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('student_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=255)),
            ],
        ),
    ]
