# Generated by Django 3.1.12 on 2025-04-26 10:24

from django.db import migrations, models
import djongo.models.fields
import ocr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardSubject',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('report_card_id', models.CharField(max_length=36)),
                ('subjects', djongo.models.fields.ArrayField(model_container=ocr.models.Subject)),
            ],
        ),
        migrations.RenameField(
            model_name='reportcard',
            old_name='academic_performance',
            new_name='school_year',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='conduct',
        ),
        migrations.RemoveField(
            model_name='reportcard',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='school',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='academic_perform_year1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='academic_perform_year2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='academic_perform_year3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='class_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year1_final',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year1_sem1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year1_sem2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year2_final',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year2_sem1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year2_sem2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year3_final',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year3_sem1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='conduct_year3_sem2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='gpa_avg_year1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='gpa_avg_year2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='gpa_avg_year3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='principal_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='promotion_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='teacher_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='teacher_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='class_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='ethnicity',
            field=models.CharField(blank=True, default='Kinh', max_length=50),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='father_job',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='guardian_job',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='mother_job',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='parents_email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='dob',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(default='Nam', max_length=10),
        ),
    ]
