# Generated by Django 3.1.12 on 2025-04-27 07:15

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20250426_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportcardsubject',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False),
        ),
    ]
