# Generated by Django 3.1.12 on 2025-04-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20250427_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
