# Generated by Django 3.1.12 on 2025-05-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
        ('ocr', '0004_reportcard_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Classroom.class'),
        ),
    ]
