# Generated by Django 3.1.12 on 2025-05-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_auto_20250501_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
