# Generated by Django 3.1.12 on 2025-05-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='teacher_id',
            field=models.CharField(default='test_teacher', max_length=36),
            preserve_default=False,
        ),
    ]
