# Generated by Django 3.1.12 on 2025-05-11 18:23

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_parent_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('recipients', models.TextField()),
                ('message', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('teacher_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
