# Generated by Django 3.1.12 on 2025-05-01 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('teacher_id', models.UUIDField()),
                ('school_name', models.CharField(max_length=255)),
                ('class_year', models.CharField(max_length=50)),
            ],
        ),
    ]
