# Generated by Django 3.1.12 on 2025-05-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher_id',
            field=models.CharField(max_length=100),
        ),
    ]
