# Generated by Django 3.1.12 on 2025-02-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.URLField()),
                ('password_hash', models.CharField(max_length=500)),
                ('fingerprint', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('last_sign_in_time', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
