# Generated by Django 3.1.12 on 2024-11-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_last_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
